# pyctest Travis CI file

cache:
  directories:
    - "${HOME}/.cache/pip"
    - "${HOME}/.pyenv"
    - "${HOME}/.cache/conda-build"

# The apt packages here install our compiled code dependencies.
jobs:
  include:
    # ------------------------------------------------------------------------ #
    #
    #   Python 3.6
    #
    # ------------------------------------------------------------------------ #
    # GCC 4.9
    - os: linux
      dist: xenial
      language: python
      python: "3.6"
      addons:
        apt:
          packages:
            - gcc
            - g++
            - build-essential
            - cmake
      env:
        - MATRIX_EVAL="CC=$(which gcc) && CXX=$(which g++) && BUILD_TYPE=RelWithDebInfo"
    # macOS
    - os: osx
      osx_image: xcode10
      language: ruby
      env:
        - MATRIX_EVAL="CC=$(which clang) && CXX=$(which clang++) && TRAVIS_PYTHON_VERSION=3.6 && MACOSX=1 && BUILD_TYPE=RelWithDebInfo"
    # ------------------------------------------------------------------------ #
    #
    #   Python 3.7
    #
    # ------------------------------------------------------------------------ #
    # GCC 4.9
    - os: linux
      dist: xenial
      language: python
      python: "3.7"
      addons:
        apt:
          packages:
            - gcc
            - g++
            - build-essential
            - cmake
      env:
        - MATRIX_EVAL="CC=$(which gcc) && CXX=$(which g++) && BUILD_TYPE=RelWithDebInfo"
    # macOS
    - os: osx
      osx_image: xcode10
      language: ruby
      env:
        - MATRIX_EVAL="CC=$(which clang) && CXX=$(which clang++) && TRAVIS_PYTHON_VERSION=3.7 && MACOSX=1 && BUILD_TYPE=RelWithDebInfo"
    # ------------------------------------------------------------------------ #
    #
    #   Python 3.8
    #
    # ------------------------------------------------------------------------ #
    # GCC 4.9
    - os: linux
      dist: xenial
      language: python
      python: "3.8"
      addons:
        apt:
          packages:
            - gcc
            - g++
            - build-essential
            - cmake
      env:
        - MATRIX_EVAL="CC=$(which gcc) && CXX=$(which g++) && BUILD_TYPE=RelWithDebInfo"
    # macOS
    - os: osx
      osx_image: xcode10
      language: ruby
      env:
        - MATRIX_EVAL="CC=$(which clang) && CXX=$(which clang++) && TRAVIS_PYTHON_VERSION=3.8 && MACOSX=1 && BUILD_TYPE=RelWithDebInfo"

before_install:
  - eval "${MATRIX_EVAL}"
  - export PYCTEST_BUILD_TYPE=${BUILD_TYPE}
  - echo "CC = ${CC} $(${CC} -dumpversion)"
  - echo "CXX = ${CXX} $(${CXX} -dumpversion)"

install:
  - eval "${MATRIX_EVAL}"
  - export VER_OS=Linux ;
  - if [[ -n "${MACOSX}" ]]; then export VER_OS=MacOSX ; fi ;
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-${VER_OS}-x86_64.sh -O miniconda.sh ;
  - bash miniconda.sh -b -p ${HOME}/miniconda ;
  - export PATH="${HOME}/miniconda/bin:${PATH}" ;
  - hash -r ;
  - conda config --set always_yes yes --set changeps1 no ;
  - conda update -q conda ;
  - conda info -a ;
  - conda install -n base -c jrmadsen -c conda-forge python=${TRAVIS_PYTHON_VERSION} pyctest ;
  - python ./pyctest-runner.py --pyctest-submit --pyctest-site=Travis

script:
  #
  # Python testing
  #
  - echo "Finished -- collapse Travis log tree"
