name: continuous-integration

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # flake8 options are defined in setup.cfg
          flake8 . --count --statistics

  linux-ci:
    runs-on: ubuntu-20.04
    continue-on-error: false
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10]
        c-compiler: ["gcc"]
        cxx-compiler: ["g++"]

    env:
      CC: ${{ matrix.c-compiler }}
      CXX: ${{ matrix.cxx-compiler }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          clean: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update container
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.c-compiler }} ${{ matrix.cxx-compiler }} build-essential cmake

      - name: Build PyCTest
        run: |
          python setup.py configure
          python setup.py install

      - name: Test PyCTest
        run: |
          pushd examples/Basic
          python basic.py -- -VV
          popd
          pushd examples/TomoPy
          python pyctest_tomopy.py --pyctest-stages State Configure Build -- -VV
          popd
